/*Program: User guesses a secret number between 1 and N. N is generated by the user. Program will prompt user 
 *         for the max number of guesses user wants to make. Each time a user makes a guess, program will
 *         respond with "correct, "too low", or "too high". Program keep track of number of guesses. 
 *         Continue until number has been discovered or max number of guesses have been made.
 *         Program will have a "play again" feature and the ability to decline
 *         Secret number generated by program 
*/

//check list:
/* generate N and # guesses
 * generate secret number (randomNumber)
 * user makes guess, 
 * displays clue
 * 
 * repeating code....somehow. Giant for loop? seems a bit costly...
 */
import java.util.Scanner;

public class SecretNumber {

	public static void main(String[] args) {
		int N = 0;
		int Attempt = 0;
		int guess = 0;
		String YorN;
		Boolean replay = true;
		
		Scanner input = new Scanner(System.in);
		System.out.println("Enter a number N");
		N = input.nextInt();
		System.out.println("Enter the number of attempts you would like to make");
		Attempt = input.nextInt();
		
		int randomNumber = (int)(N* Math.random()) + 1;
		
		System.out.println("Make your guess");
		guess = input.nextInt();
		
		for (int i = 1; i <=Attempt; i++) {                 //loops till all attempts are made
			if(guess == randomNumber) {
				System.out.println("Correct");              //breaks when correct guess is made
				i = Attempt;
			}
			else if (guess > randomNumber) {                //gives clue prompts another entry
				System.out.println("too high");
				System.out.println("Try again");
				guess = input.nextInt();
			}
			else if (guess < randomNumber) {                //gives clue prompts another entry 
				System.out.println("too low");
				System.out.println("Try again");
				guess= input.nextInt();
					
			}
		}	
	}		
}
